fraud:
   outputs:
      dev:
         account: replace_with_yours
         database: AIRBYTE_DATABASE
         password: snowflake
         role: AIRBYTE_ROLE
         schema: prod
         threads: 1
         type: snowflake
         user: AIRBYTE_USER
         warehouse: AIRBYTE_WAREHOUSE
   target: dev
